# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99349a96d9061e3a0181ffdf9a679df2178138dd90c5291b9e24155ac1e21529fcc9aad6e5bdf9b98ae7f83af2079ec5b5bc594ccc5e683549fc0758965a97c3

test:
  secret_key_base: 0f0113d87b219133ddff502501e42fc1d97c2581f85983b563e9036a85a4d359cf8f4b039ceee8831686557480ca93415941f48a27e612348e048d66a75487a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
